In [43]:
import numpy as np

In [44]:
iris = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype = 'float', usecols=[0,1,2,3])

In [45]:
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [46]:
a=iris[1]

In [47]:
boo = ( iris - a )**2

In [48]:
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True)

In [49]:
boo

array([[ 0.04,  0.25,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.04,  0.04,  0.01,  0.  ],
       [ 0.09,  0.01,  0.01,  0.  ],
       [ 0.01,  0.36,  0.  ,  0.  ],
       [ 0.25,  0.81,  0.09,  0.04],
       [ 0.09,  0.16,  0.  ,  0.01],
       [ 0.01,  0.16,  0.01,  0.  ],
       [ 0.25,  0.01,  0.  ,  0.  ],
       [ 0.  ,  0.01,  0.01,  0.01],
       [ 0.25,  0.49,  0.01,  0.  ],
       [ 0.01,  0.16,  0.04,  0.  ],
       [ 0.01,  0.  ,  0.  ,  0.01],
       [ 0.36,  0.  ,  0.09,  0.01],
       [ 0.81,  1.  ,  0.04,  0.  ],
       [ 0.64,  1.96,  0.01,  0.04],
       [ 0.25,  0.81,  0.01,  0.04],
       [ 0.04,  0.25,  0.  ,  0.01],
       [ 0.64,  0.64,  0.09,  0.01],
       [ 0.04,  0.64,  0.01,  0.01],
       [ 0.25,  0.16,  0.09,  0.  ],
       [ 0.04,  0.49,  0.01,  0.04],
       [ 0.09,  0.36,  0.16,  0.  ],
       [ 0.04,  0.09,  0.09,  0.09],
       [ 0.01,  0.16,  0.25,  0.  ],
       [ 0.01,  0.  ,  0.04,  0.  ],
       [ 0.01,  0.16,  0.04,  0.04],
 

In [50]:
euclidean_distances = list(map(lambda x: sum(x)**0.5, boo)) 
closest_fives = np.argsort(euclidean_distances)[:5]

In [51]:
euclidean_distances = np.array(euclidean_distances)

In [52]:
euclidean_distances[np.argsort(euclidean_distances)]

array([0.  , 0.14, 0.14, 0.17, 0.17, 0.17, 0.22, 0.24, 0.3 , 0.3 , 0.32,
       0.33, 0.35, 0.36, 0.42, 0.46, 0.46, 0.5 , 0.5 , 0.51, 0.51, 0.51,
       0.53, 0.54, 0.55, 0.55, 0.56, 0.59, 0.61, 0.65, 0.68, 0.68, 0.68,
       0.71, 0.76, 0.78, 0.79, 0.81, 0.82, 0.84, 0.85, 0.87, 0.98, 1.05,
       1.09, 1.15, 1.17, 1.34, 1.36, 1.63, 1.91, 2.15, 2.18, 2.42, 2.46,
       2.56, 2.58, 2.7 , 2.79, 2.81, 2.85, 2.93, 2.95, 2.97, 2.97, 3.  ,
       3.03, 3.04, 3.07, 3.08, 3.1 , 3.11, 3.24, 3.24, 3.36, 3.39, 3.4 ,
       3.43, 3.45, 3.48, 3.54, 3.56, 3.6 , 3.62, 3.65, 3.66, 3.69, 3.69,
       3.7 , 3.71, 3.79, 3.81, 3.86, 3.89, 3.92, 3.98, 3.98, 4.  , 4.02,
       4.03, 4.06, 4.08, 4.1 , 4.11, 4.12, 4.13, 4.15, 4.17, 4.18, 4.18,
       4.24, 4.25, 4.3 , 4.4 , 4.42, 4.5 , 4.52, 4.55, 4.65, 4.68, 4.68,
       4.7 , 4.7 , 4.71, 4.72, 4.85, 4.86, 4.89, 4.9 , 4.96, 5.04, 5.04,
       5.07, 5.09, 5.16, 5.19, 5.21, 5.32, 5.34, 5.36, 5.39, 5.59, 5.69,
       5.75, 5.86, 6.15, 6.16, 6.26, 6.37, 6.53])

In [53]:
closest_fives

array([ 1, 45, 12,  9, 34], dtype=int64)

In [54]:
euclidean_distances = np.array(euclidean_distances)

In [55]:
euc_dist = euclidean_distances[closest_fives] # euclidean distances of the closest fives
euc_dist

array([0.  , 0.14, 0.14, 0.17, 0.17])

In [56]:
euc_vecs = boo[closest_fives] 
euc_vecs 


array([[0.  , 0.  , 0.  , 0.  ],
       [0.01, 0.  , 0.  , 0.01],
       [0.01, 0.  , 0.  , 0.01],
       [0.  , 0.01, 0.01, 0.01],
       [0.  , 0.01, 0.01, 0.01]])

In [57]:
list(zip(euc_vecs, euc_dist))

[(array([0., 0., 0., 0.]), 0.0),
 (array([0.01, 0.  , 0.  , 0.01]), 0.14142135623730986),
 (array([0.01, 0.  , 0.  , 0.01]), 0.1414213562373099),
 (array([0.  , 0.01, 0.01, 0.01]), 0.17320508075688784),
 (array([0.  , 0.01, 0.01, 0.01]), 0.17320508075688784)]

In [58]:
abs(iris - 10) 

array([[4.9, 6.5, 8.6, 9.8],
       [5.1, 7. , 8.6, 9.8],
       [5.3, 6.8, 8.7, 9.8],
       [5.4, 6.9, 8.5, 9.8],
       [5. , 6.4, 8.6, 9.8],
       [4.6, 6.1, 8.3, 9.6],
       [5.4, 6.6, 8.6, 9.7],
       [5. , 6.6, 8.5, 9.8],
       [5.6, 7.1, 8.6, 9.8],
       [5.1, 6.9, 8.5, 9.9],
       [4.6, 6.3, 8.5, 9.8],
       [5.2, 6.6, 8.4, 9.8],
       [5.2, 7. , 8.6, 9.9],
       [5.7, 7. , 8.9, 9.9],
       [4.2, 6. , 8.8, 9.8],
       [4.3, 5.6, 8.5, 9.6],
       [4.6, 6.1, 8.7, 9.6],
       [4.9, 6.5, 8.6, 9.7],
       [4.3, 6.2, 8.3, 9.7],
       [4.9, 6.2, 8.5, 9.7],
       [4.6, 6.6, 8.3, 9.8],
       [4.9, 6.3, 8.5, 9.6],
       [5.4, 6.4, 9. , 9.8],
       [4.9, 6.7, 8.3, 9.5],
       [5.2, 6.6, 8.1, 9.8],
       [5. , 7. , 8.4, 9.8],
       [5. , 6.6, 8.4, 9.6],
       [4.8, 6.5, 8.5, 9.8],
       [4.8, 6.6, 8.6, 9.8],
       [5.3, 6.8, 8.4, 9.8],
       [5.2, 6.9, 8.4, 9.8],
       [4.6, 6.6, 8.5, 9.6],
       [4.8, 5.9, 8.5, 9.9],
       [4.5, 5.8, 8.6, 9.8],
       [5.1, 6

In [59]:
manhattan_distances = abs(iris - a)

In [60]:
manhattan_distances = list(map(lambda x: sum(x), manhattan_distances)) 

In [61]:
manhattan_distances = np.array(manhattan_distances)

In [62]:
closest_fives = np.argsort(manhattan_distances)[:5]

In [63]:
man_dist = manhattan_distances[closest_fives]
man_vecs = iris[closest_fives]

In [64]:
list(zip(man_vecs, man_dist))

[(array([4.9, 3. , 1.4, 0.2]), 0.0),
 (array([4.8, 3. , 1.4, 0.3]), 0.2000000000000005),
 (array([4.8, 3. , 1.4, 0.1]), 0.20000000000000054),
 (array([5. , 3. , 1.6, 0.2]), 0.2999999999999998),
 (array([4.9, 3.1, 1.5, 0.1]), 0.30000000000000016)]

# QUES  1 and 2 COMPLETED

In [65]:
# Create a CSV file to store the roll number and marks of five subjects of the students. 
# Find the mean of the marks of each student as well as total mean of the data stored. 
# Select the best case, average case and worst case using the means calculated. 
# Display the roll number of these three types of students.

In [66]:
import os
os.getcwd()
os.remove("student_marks.csv")

In [67]:
marks_range = range(1,100)
subjects = 5
num_students = 30 

In [68]:

import csv
import random

with open('student_marks.csv', 'x') as f: 
    writer = csv.writer(f)
    
    for student in range(num_students):
        student_marksheet = random.sample(marks_range, subjects) 
        writer.writerow(student_marksheet)

In [69]:
markshit = np.genfromtxt('student_marks.csv', delimiter=',', dtype = 'int')

In [70]:
markshit 

array([[46, 20, 94, 50, 72],
       [25, 71, 55, 45, 31],
       [23, 24, 38, 60, 92],
       [24, 28,  5, 42, 23],
       [23, 13, 41, 21, 53],
       [40, 66, 64, 19, 13],
       [75,  2,  4, 66, 94],
       [42, 10, 70,  1, 34],
       [34, 28, 25, 44,  8],
       [76, 32, 51, 26, 31],
       [13, 12, 55, 40, 43],
       [62, 66, 54, 46, 98],
       [99, 75, 68,  5, 56],
       [68, 77, 24, 13, 47],
       [66, 52, 22, 92, 33],
       [ 2, 84,  3, 63, 49],
       [77, 48, 95, 27, 13],
       [97, 62, 53, 75, 61],
       [97, 15, 58, 63, 86],
       [ 6, 35, 17, 98, 27],
       [20, 83, 48, 52, 79],
       [74, 65, 49, 85, 87],
       [76, 61, 24, 36, 16],
       [ 5, 70, 12, 31,  1],
       [43, 72, 51, 92, 55],
       [27, 66,  8, 75, 34],
       [89, 44, 92, 97, 83],
       [ 6, 56, 78, 35, 17],
       [52, 75, 17, 45, 31],
       [77, 48, 11, 84, 29]])

In [71]:
mean_each_student = list(map(lambda student_marks: sum(student_marks)/subjects, markshit)) 

In [72]:
np.mean(mean_each_student)  

47.559999999999995

In [73]:
print('The mean marks are :' ,np.mean(markshit))

The mean marks are : 47.56


In [74]:
worst_case, avg_case, best_case = min(mean_each_student), np.mean(mean_each_student), max(mean_each_student)

In [75]:
np.std(mean_each_student) 

14.219273305388477

In [76]:
neighbs = abs(np.array(mean_each_student) - avg_case)
nearest_avg_case = np.argmin(neighbs)

In [77]:
print('The worst student award goes to : ', np.where(mean_each_student == worst_case)[0][0])
print('The most average student is : ', nearest_avg_case)
print('The best student award goes to : ', np.where(mean_each_student == best_case)[0][0])

The worst student award goes to :  23
The most average student is :  2
The best student award goes to :  26


# QUES 3 COMPLETED

In [78]:
# Generate a random sequence and 
# then pick up the samples from the CSV file stored in iris dataset. 
# Then find the mean and standard deviation of these randomly selected samples.

In [79]:
rows_iris = len(iris) 

In [80]:
random_rows = random.sample(range(0, rows_iris), 10) 


In [81]:
random_rows

[20, 27, 63, 58, 1, 126, 146, 49, 25, 18]

In [82]:
random_iris = iris[random_rows]

In [83]:
features = ['Sepal_length', 'Sepal_width', 'Petal_length', 'Petal_width']
for column in range(iris.shape[1]):
    mean = np.mean(random_iris[:, column])
    std = np.std(random_iris[:, column])
    print( str(features[column]) )  
    print('Mean : ', mean)
    print('Standard Deviation : ', std)

Sepal_length
Mean :  5.640000000000001
Standard Deviation :  0.5919459434779495
Sepal_width
Mean :  3.11
Standard Deviation :  0.36455452267116367
Petal_length
Mean :  2.8400000000000003
Standard Deviation :  1.5856859714331837
Petal_width
Mean :  0.7699999999999999
Standard Deviation :  0.6972087205421342


## QUES 4 Completed