In [1]:
import numpy as np

In [2]:
#q1
a=[1,2,3,4,5,6,7,8,9]
b=[]
c=[]
for i in a:
    if i%2==0 :
        b.append(i)
    else :
        c.append(i)
print(a)
print(b)
print(c)
    

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 4, 6, 8]
[1, 3, 5, 7, 9]


In [3]:
#Q2
a=[1,2,3,4,5,6,7,8,9]
for i in range(0,len(a)):
    if a[i]%2!=0:
        a[i]="odd"
b=np.array(a)
print(b)


['odd' '2' 'odd' '4' 'odd' '6' 'odd' '8' 'odd']


In [4]:
#q3
b=np.array(['How','are','you'])
np.append(np.resize(b.T,(3,3)).T.flatten(),np.resize(b,(3,3)).flatten())

array(['How', 'How', 'How', 'are', 'are', 'are', 'you', 'you', 'you',
       'How', 'are', 'you', 'How', 'are', 'you', 'How', 'are', 'you'],
      dtype='<U3')

In [5]:
#q4
a=np.array(['a','b','c','d'])
b=np.array(['a','c','e'])
np.intersect1d(a,b)
    


array(['a', 'c'], dtype='<U1')

In [6]:
#Q5
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a[:,[0,2]]=a[:,[2,0]]
print(a)
a[[0,1],:]=a[[1,0],:]
print(a)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[6 5 4]
 [3 2 1]
 [9 8 7]]


In [7]:
#Q6
a=np.random.randint(low=6,high=12,size=15)
np.resize(a,(5,3))


array([[ 7, 11,  6],
       [ 7, 11, 10],
       [ 6,  8, 10],
       [ 6,  7,  9],
       [11, 10,  9]])

In [9]:
#q7
a=np.random.rand(10)
np.round(a,2)
    

array([0.82, 0.27, 0.25, 0.83, 0.22, 0.35, 0.85, 0.49, 0.02, 0.13])

In [12]:
#q8
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=None)
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

<ipython-input-12-c6d49f3795f2>:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris = np.genfromtxt(url, delimiter=',', dtype=None)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [13]:
#q9
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409
