**Aditya Ranaut**

**101916012**

**ML Assignment 5**


In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression


In [ ]:
df=pd.read_csv("adi2.csv")

In [ ]:
print(df)

   Square Feet\n(X)  House Price in $1000s\n(Y)
0              1400                         245
1              1600                         312
2              1700                         279
3              1875                         308
4              1100                         199
5              1550                         219
6              2350                         405
7              2450                         324
8              1425                         319
9              1700                         255


In [ ]:
X = df.iloc[:, :-1].values
print(X)

[[1400]
 [1600]
 [1700]
 [1875]
 [1100]
 [1550]
 [2350]
 [2450]
 [1425]
 [1700]]


In [ ]:
Y = df.iloc[:, -1].values
print(Y)

[245 312 279 308 199 219 405 324 319 255]


In [ ]:
reg = LinearRegression()

In [ ]:
reg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
print('Coefficients: ', reg.coef_)

Coefficients:  [0.10976774]


In [ ]:
print(reg.predict([[3000]]))

[427.55154311]


In [ ]:
print(reg.predict([[2000]]))

[317.78380528]


In [ ]:
print(reg.predict([[1500]]))

[262.89993637]


In [ ]:
df2=pd.read_csv("adi1.csv")

In [ ]:
print(df2)

    Year  Month  lnterest_Rate  Unemployment_Rate  Stock_lndex_Price
0   2017     12           2.75                5.3               1464
1   2017     11           2.50                5.3               1394
2   2017     10           2.50                5.3               1357
3   2017      9           2.50                5.3               1293
4   2017      8           2.50                5.4               1256
5   2017      7           2.50                5.6               1254
6   2017      6           2.50                5.5               1234
7   2017      5           2.25                5.5               1195
8   2017      4           2.25                5.5               1159
9   2017      3           2.25                5.6               1167
10  2017      2           2.00                5.7               1130
11  2017      1           2.00                5.9               1075
12  2016     12           2.00                6.0               1047
13  2016     11           1.75    

In [ ]:
X2 = df2.iloc[:, :-1].values
print(X2)

[[2.017e+03 1.200e+01 2.750e+00 5.300e+00]
 [2.017e+03 1.100e+01 2.500e+00 5.300e+00]
 [2.017e+03 1.000e+01 2.500e+00 5.300e+00]
 [2.017e+03 9.000e+00 2.500e+00 5.300e+00]
 [2.017e+03 8.000e+00 2.500e+00 5.400e+00]
 [2.017e+03 7.000e+00 2.500e+00 5.600e+00]
 [2.017e+03 6.000e+00 2.500e+00 5.500e+00]
 [2.017e+03 5.000e+00 2.250e+00 5.500e+00]
 [2.017e+03 4.000e+00 2.250e+00 5.500e+00]
 [2.017e+03 3.000e+00 2.250e+00 5.600e+00]
 [2.017e+03 2.000e+00 2.000e+00 5.700e+00]
 [2.017e+03 1.000e+00 2.000e+00 5.900e+00]
 [2.016e+03 1.200e+01 2.000e+00 6.000e+00]
 [2.016e+03 1.100e+01 1.750e+00 5.900e+00]
 [2.016e+03 1.000e+01 1.750e+00 5.800e+00]
 [2.016e+03 9.000e+00 1.750e+00 6.100e+00]
 [2.016e+03 8.000e+00 1.750e+00 6.200e+00]
 [2.016e+03 7.000e+00 1.750e+00 6.100e+00]
 [2.016e+03 6.000e+00 1.750e+00 6.100e+00]
 [2.016e+03 5.000e+00 1.750e+00 6.100e+00]
 [2.016e+03 4.000e+00 1.750e+00 5.900e+00]
 [2.016e+03 3.000e+00 1.750e+00 6.200e+00]
 [2.016e+03 2.000e+00 1.750e+00 6.200e+00]
 [2.016e+03

In [ ]:
Y2 = df2.iloc[:, -1].values
print(Y2)

[1464 1394 1357 1293 1256 1254 1234 1195 1159 1167 1130 1075 1047  965
  943  958  971  949  884  866  876  822  704  719]


In [ ]:
reg2 = LinearRegression()

In [ ]:
reg2.fit(X2,Y2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
print(reg2.predict([[2021,9,1.5,5.8]]))

[2621.77182291]
